{
	"meta":	{
	  "code": 200
	},
	"data": {
	  "object": "user",
	  "object_id": null,
  	  "aspect": "media",
	  "callback_url": "http:\/\/serverrummet.dk\/ib\/cb.php",
	  "type": "subscription",
	  "id": "3353683"
	}
}




https://api.instagram.com/v1/subscriptions?client_secret=CLIENT-SECRET&client_id=CLIENT-ID
https://api.instagram.com/v1/subscriptions?client_secret=d72e5843b4d846fe8d9f184cc4af3814&client_id=48e3a611d4484383bb87ca5c528c7cef

curl -X DELETE https://api.instagram.com/v1/subscriptions?client_secret=d72e5843b4d846fe8d9f184cc4af3814&client_id=48e3a611d4484383bb87ca5c528c7cef&object=all
